import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import { UseContext } from '@/lib/Appcontext'
import { GetServerSideProps, NextPage } from 'next';
import Footer from '@/components/Footer';
import FillImage from '@/components/FillImage';
import Navbar from '@/components/Navbar';
interface Props {

  lang: string
}

const Home: NextPage<Props> = (props) => {

  const context = UseContext();


  return (
    <>
      <Head>
        <title>Iniciar sesion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div>
          <Navbar isLogged={false} />
        </div>
        <div className='mb-5'>
          <div className={`${styles.containerImage}`}>
            <div className={styles.containerVideo}>
              <video className={styles.video} autoPlay muted loop>
                <source src="video.mp4" type="video/mp4" />
              </video>
              <div className={`${styles.buyNowButtonContainer}`}>
                <input  type="button" className={`${styles.buttonBuyNow} btn btn-success btn-lg`} value={"Comprar ahora"} />
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </Layout>
    </>
  )
}

export default Home;


export const getServerSideProps: GetServerSideProps = async (context) => {

  return {

    props: {

      lang: context.locale
    }
  }
}