import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import { UseContext } from '@/lib/Appcontext'
import { GetServerSideProps, NextPage } from 'next';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import Products from '@/components/Products';
import { getReviews } from '@/lib/reviews/getReviews';
import { withSessionSsr } from '@/lib/auth/session';
import { useEffect } from 'react';
import { SessionUserType, dataUserSession } from '@/lib/auth/sessionusertype';
import { getProductsFirebase } from '@/lib/firebase';
interface Props {

  lang: string,
  comments: Array<any>,
  products: Array<any>,
  user : SessionUserType
}



const Home: NextPage<Props> = (props) => {

  const context = UseContext();
  

  useEffect(() => {
    
    context.setCountCart(props.user);
    context.setLang(props.lang);

    return () => {

       context.setLang("");
    }

  }, [props.user]);



  return (
    <>
      <Head>
        <title>Iniciar sesion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div>
          <Navbar isLogged={false} lang={props.lang} products={props.products} />
        </div>
        <div className='mb-5'>
          <div className={`${styles.containerImage}`}>
            <div className={styles.containerVideo}>
              <video className={styles.video} autoPlay muted loop>
                <source src="video.mp4" type="video/mp4" />
              </video>
              <div className={`${styles.buyNowButtonContainer}`}>
                <input type="button" className={`${styles.buttonBuyNow} btn btn-success btn-lg`}  value={"Comprar ahora"} />
              </div>
            </div>
          </div>
          <Products products={props.products} coments={props.comments} />
        </div>
        <Footer />
      </Layout>
    </>
  )
}

export default Home;


export const getServerSideProps: GetServerSideProps = withSessionSsr(
  async function getServerSideProps(context) {


    const reviews = await getReviews();
    const products = await getProductsFirebase();
    


    return {
      props: {
        user: context.req.session.user || dataUserSession,
        lang: context.locale,
        comments: reviews,
        products: products
      },
    };
  },
);